auth:
  api:
    url: http://auth-app:8012
  expose:
    url: actuator

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: http://broker:9092